# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = EmbDBStudio
QT += core
include(EmbDBStudio.pri)
