#ifndef _EMBEDDED_DATABASE_FILE_PAGE_TYPE_H_
#define _EMBEDDED_DATABASE_FILE_PAGE_TYPE_H_
namespace embDB
{
	enum eObjectPageType
	{
		DATABASE_PAGE = 1,
		SCHEMA_PAGE,
		TABLE_PAGE,
		BTREE_PAGE,
		FIELD_PAGE,
		FREE_PAGE_LIST,
		STORAGE_PAGE,
		TRANSACTION_PAGE,
		INDEX_PAGE,
		TRAN_MANAGE_PAGE
	};
	enum eDatabasePageType
	{
		DB_HEADER_PAGE,
		DB_ROOT_PAGE,
		DB_ROOT_USER_PAGE
		
	};

	enum eBtreeTypePage
	{
		BTREE_ROOT_PAGE,
		BTREE_LEAF_PAGE,
		BTREE_INNER_PAGE,
		BTREE_STATIC_PAGE,
		BTREE_INFO_PAGE,
		BTREE_STRING_PARAMS_COMPRESS_PAGE,
		BTREE_BLOB_PARAMS_COMPRESS_PAGE,
		BTREE_STREAM_PAGE_INFO,
		BTREE_SHAPE_PARAMS_COMPRESS_PAGE
	};

	enum eTableTypePage
	{
		TABLE_HEADER_PAGE,
		TABLE_FIELD_PAGE,
		TABLE_FIELD_LIST_PAGE,
		TABLE_INDEX_LIST_PAGE,
		TABLE_INDEX_PAGE,
		TABLE_STORAGE_PAGE,
		TABLE_OID_COUNTER_PAGE,
		TABLE_STATISTICS_LIST_PAGE,
		TABLE_STATISTICS_PAGE,
	};

	enum eSchemaPageType
	{
		SCHEMA_ROOT_PAGE,
		SCHEMA_TABLE_LIST_PAGE
	};

	enum eStoragePageType
	{
		STORAGE_INFO_PAGE,
		STORAGE_FREE_MAP_ROOT_PAGE,
		STORAGE_LIST_FREEMAP_PAGE,
		STORAGE_FREE_MAP_PAGE
	};

	enum eFieldPageType
	{
		FIELD_INFO_PAGE,
		FIELD_INFO_STATISTIC
 	};


	enum ePageStatisticType
	{
		FIELD_FULL_STATISTIC
	};

	enum eIndexPageType
	{
		INDEX_INFO_PAGE,
		MULTI_INDEX_INFO_PAGE,
		COMP_INDEX_INFO_PAGE
	};

	enum eTransactionsPageType
	{
		UNDO_PAGES,
		UNDO_FREEMAP_PAGES_ROOT,
		UNDO_FREEMAP_PAGES_LIST,
		REDO_PAGES
	};

	enum eTransactionsManagePage
	{
		TM_HEADER_PAGE
	};
}
#endif