# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = GeoConvertor
QT += core widgets gui
include(GeoConvertor.pri)
